/** Production company + branch master data for MER dropdowns */
export const COMPANIES_SEED = [
  {
    name: 'Baid Inbest Llp',
    email: 'billp.contactus@inbestnow.com',
    phone: '8981541333',
    taxId: '19AALFB4917G1ZB',
    website: '',
    logo: '',
    companyCode: 'BILLP',
    isActive: true,
    locations: [
      {
        label: 'HQ',
        street: '6th Floor, Suite No 608 And 609, Ashoka House, 3a, Hare St, B.b.d. Bagh',
        city: 'Kolkata',
        state: 'West Bengal',
        zipCode: '700001',
        country: 'India',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Baid Solutions Insurance Broking Private Limited',
    email: 'admin@inbestnow.com',
    phone: '8981541333',
    taxId: '19AAECB8825F1ZJ',
    website: '',
    logo: '',
    companyCode: 'BSIBPL',
    isActive: true,
    locations: [
      {
        label: 'HQ',
        street: '6th Floor, Suite No 608 And 609, Ashoka House, 3a, Hare St, B.b.d. Bagh',
        city: 'Kolkata',
        state: 'West Bengal',
        zipCode: '700001',
        country: 'India',
        isDefault: true,
      },
      {
        label: 'BRO 1',
        street: '14, Subhash Marg, C Scheme, Ashok Nagar',
        city: 'Jaipur',
        state: 'Rajasthan',
        zipCode: '302001',
        country: 'India',
        isDefault: false,
      },
      {
        label: 'BRO 2',
        street: 'Vasanth Nagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        zipCode: '560001',
        country: 'India',
        isDefault: false,
      },
    ],
  },
  {
    name: 'Bnb Agro',
    email: 'admin@inbestnow.com',
    phone: '8981541333',
    taxId: '19ABGFB6150K1Z8',
    website: '',
    logo: '',
    companyCode: 'BNB-AGRO',
    isActive: true,
    locations: [
      {
        label: 'HQ',
        street:
          '6th Floor, Jasmine Tower , Unit No - 611 , Name Of Premises/building: 31 , Shakespeare Sarani',
        city: 'Kolkata',
        state: 'West Bengal',
        zipCode: '700017',
        country: 'India',
        isDefault: true,
      },
    ],
  },
];
